name: Deploy MultiDocker
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      # build docker image
      - run: docker build -t torris212/docker-react -f Dockerfile.dev .
      # run container
      - run: docker run -e CI=true torris212/docker-react npm test

      # - run: docker build -t cygnetops/multi-client-10-14 ./client
      # - run: docker build -t cygnetops/multi-nginx-10-14 ./nginx
      # - run: docker build -t cygnetops/multi-server-10-14 ./server
      # - run: docker build -t cygnetops/multi-worker-10-14 ./worker

      # - run: docker push cygnetops/multi-client-10-14
      # - run: docker push cygnetops/multi-nginx-10-14
      # - run: docker push cygnetops/multi-server-10-14
      # - run: docker push cygnetops/multi-worker-10-14

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: docker-react
          environment_name: Docker-react-env
          existing_bucket_name: elasticbeanstalk-us-east-1-045054254260
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip